### ISSUE TITLE
Windows Defender and AVG report Windows executable infected with a virus

### ISSUE THREAD

**Issue by netcompsys** [tasmota/tasmotizer#10]
![Screenshot 2019-12-23 12 52 30 (2)](https://user-images.githubusercontent.com/11429957/71359309-f172d680-2583-11ea-828d-d62c0ff810de.jpg)

If you want to use this you have to disable Antivirus otherwise it removes it automatically

**Comment by jziolkowski** [comment]
As it is written on the main page of the repo, it's a known false positive. Add it to whitelist and it's fixed.

**Comment by netcompsys** [comment]
It is still an issue, making a comment and closing it does not fix the problem

**Comment by jziolkowski** [comment]
False positive is a problem of antivirus, not ours. Or at least, it's pyinstaller problem, because this is what is used for packaging to .exe

Googling that error shows that antivirus companies give little attention to such reports and raised issues. So it's a bit of a ping-pong game of who should fix that. And when an antivirus mistakenly treats some code as malicious, it's not our responsibility to fix their problem.
