### ISSUE TITLE
Backup file size

### ISSUE THREAD

**Issue by ashoktvm** [tasmota/tasmotizer#13]
Why is the backup more than 1 MB? How can a less than 1mb memory device restore backup which have more than 1MB?

Also stuck after flashing
![image](https://user-images.githubusercontent.com/45116583/71640131-4ca27880-2caa-11ea-9996-567e99a0607a.png)
Keeps like this for several minutes

**Comment by jziolkowski** [comment]
I just tested a backup on a NodeMCU and it's exactly 1MB. As for why yours are bigger you'll have to take it up to esptool github because I only save what it's giving back from your ESP via the USB adapter. The progress dialog listens to what esptool is returning as when you would run it manually, and if esptool is stuck, then tasmotizer will be stuck as well.

**Comment by jziolkowski** [comment]
Closed due to inactivity.
